package com.example.data.pdf

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.os.Environment
import androidx.core.content.FileProvider
import com.example.data.model.Book
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream

object PdfExporter {

    private const val PAGE_WIDTH = 595 // Standard A4 width in points (72 dpi)
    private const val PAGE_HEIGHT = 842 // Standard A4 height in points (72 dpi)
    private const val MARGIN_HORIZONTAL = 48f
    private const val MARGIN_VERTICAL = 54f
    private const val LINE_SPACING_FACTOR = 1.35f

    suspend fun generateBookPdf(
        context: Context,
        book: Book,
        bookText: String,
        onProgress: (Float) -> Unit = {}
    ): File = withContext(Dispatchers.IO) {
        val document = PdfDocument()

        val titlePaint = Paint().apply {
            color = Color.parseColor("#0F172A")
            textSize = 24f
            typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
            isAntiAlias = true
        }

        val authorPaint = Paint().apply {
            color = Color.parseColor("#334155")
            textSize = 15f
            typeface = Typeface.create(Typeface.SERIF, Typeface.ITALIC)
            isAntiAlias = true
        }

        val metaPaint = Paint().apply {
            color = Color.parseColor("#64748B")
            textSize = 11f
            typeface = Typeface.DEFAULT
            isAntiAlias = true
        }

        val bodyPaint = Paint().apply {
            color = Color.parseColor("#1E293B")
            textSize = 12f
            typeface = Typeface.SERIF
            isAntiAlias = true
        }

        val headerFooterPaint = Paint().apply {
            color = Color.parseColor("#94A3B8")
            textSize = 9f
            typeface = Typeface.SERIF
            isAntiAlias = true
        }

        val rulePaint = Paint().apply {
            color = Color.parseColor("#CBD5E1")
            strokeWidth = 1f
            style = Paint.Style.STROKE
            isAntiAlias = true
        }

        val printableWidth = PAGE_WIDTH - (MARGIN_HORIZONTAL * 2)
        val printableHeight = PAGE_HEIGHT - (MARGIN_VERTICAL * 2)

        // 1. Title Page
        var pageNumber = 1
        val coverPageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
        val coverPage = document.startPage(coverPageInfo)
        val coverCanvas: Canvas = coverPage.canvas

        // Background subtle tint
        val bgPaint = Paint().apply { color = Color.parseColor("#F8FAFC") }
        coverCanvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), PAGE_HEIGHT.toFloat(), bgPaint)

        // Decorative border
        val borderPaint = Paint().apply {
            color = Color.parseColor("#E2E8F0")
            strokeWidth = 2f
            style = Paint.Style.STROKE
        }
        coverCanvas.drawRect(24f, 24f, PAGE_WIDTH - 24f, PAGE_HEIGHT - 24f, borderPaint)

        // Draw title
        var titleY = 240f
        val wrappedTitle = breakTextIntoLines(book.title, titlePaint, printableWidth)
        for (line in wrappedTitle) {
            coverCanvas.drawText(line, MARGIN_HORIZONTAL, titleY, titlePaint)
            titleY += titlePaint.textSize * 1.3f
        }

        titleY += 24f
        coverCanvas.drawLine(MARGIN_HORIZONTAL, titleY, MARGIN_HORIZONTAL + 80f, titleY, rulePaint)
        titleY += 32f

        coverCanvas.drawText("By ${book.displayAuthor}", MARGIN_HORIZONTAL, titleY, authorPaint)
        titleY += 36f

        if (book.primarySubject.isNotBlank()) {
            coverCanvas.drawText("Category: ${book.primarySubject}", MARGIN_HORIZONTAL, titleY, metaPaint)
            titleY += 20f
        }

        // Bottom notice
        val bottomY = PAGE_HEIGHT - 90f
        coverCanvas.drawText("Free Public Domain Edition • Project Gutenberg", MARGIN_HORIZONTAL, bottomY, metaPaint)
        coverCanvas.drawText("Generated by FreeBooks App for offline reading", MARGIN_HORIZONTAL, bottomY + 18f, metaPaint)

        document.finishPage(coverPage)
        onProgress(0.05f)

        // 2. Body Text Pages
        val lineHeight = bodyPaint.textSize * LINE_SPACING_FACTOR
        val rawParagraphs = bookText.split("\n")
        val lines = mutableListOf<String>()

        for (paragraph in rawParagraphs) {
            val trimmed = paragraph.trimEnd()
            if (trimmed.isEmpty()) {
                lines.add("") // Paragraph break
            } else {
                lines.addAll(breakTextIntoLines(trimmed, bodyPaint, printableWidth))
            }
        }

        val totalLines = lines.size
        var lineIndex = 0

        // Limit pages to prevent OutOfMemory on huge 500k-line books if any
        val maxPages = 150.coerceAtMost((totalLines / 40) + 5)

        while (lineIndex < totalLines && pageNumber < maxPages) {
            pageNumber++
            val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
            val page = document.startPage(pageInfo)
            val canvas: Canvas = page.canvas

            // Running Header
            val headerText = "${book.title.take(35)} • ${book.displayAuthor.take(25)}"
            canvas.drawText(headerText, MARGIN_HORIZONTAL, MARGIN_VERTICAL - 20f, headerFooterPaint)
            canvas.drawLine(MARGIN_HORIZONTAL, MARGIN_VERTICAL - 12f, PAGE_WIDTH - MARGIN_HORIZONTAL, MARGIN_VERTICAL - 12f, rulePaint)

            // Content lines
            var currentY = MARGIN_VERTICAL + 15f
            val maxY = PAGE_HEIGHT - MARGIN_VERTICAL - 15f

            while (lineIndex < totalLines && currentY + lineHeight <= maxY) {
                val currentLine = lines[lineIndex]
                if (currentLine.isNotEmpty()) {
                    canvas.drawText(currentLine, MARGIN_HORIZONTAL, currentY, bodyPaint)
                }
                currentY += lineHeight
                lineIndex++
            }

            // Running Footer
            val footerText = "Page $pageNumber"
            val textWidth = headerFooterPaint.measureText(footerText)
            canvas.drawText(footerText, PAGE_WIDTH - MARGIN_HORIZONTAL - textWidth, PAGE_HEIGHT - MARGIN_VERTICAL + 24f, headerFooterPaint)
            canvas.drawLine(MARGIN_HORIZONTAL, PAGE_HEIGHT - MARGIN_VERTICAL + 12f, PAGE_WIDTH - MARGIN_HORIZONTAL, PAGE_HEIGHT - MARGIN_VERTICAL + 12f, rulePaint)

            document.finishPage(page)

            val progress = 0.05f + (0.90f * (lineIndex.toFloat() / totalLines.coerceAtLeast(1)))
            onProgress(progress.coerceAtMost(0.95f))
        }

        // Save PDF to downloads directory
        val sanitizedTitle = book.title
            .replace(Regex("[^a-zA-Z0-9.-]"), "_")
            .take(40)
        val downloadDir = context.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS)
            ?: context.filesDir
        if (!downloadDir.exists()) downloadDir.mkdirs()

        val pdfFile = File(downloadDir, "${sanitizedTitle}_ID${book.id}.pdf")
        FileOutputStream(pdfFile).use { out ->
            document.writeTo(out)
        }
        document.close()

        onProgress(1.0f)
        pdfFile
    }

    private fun breakTextIntoLines(text: String, paint: Paint, maxWidth: Float): List<String> {
        val result = mutableListOf<String>()
        val words = text.split(" ")
        var currentLine = StringBuilder()

        for (word in words) {
            val testLine = if (currentLine.isEmpty()) word else "$currentLine $word"
            val width = paint.measureText(testLine)
            if (width <= maxWidth) {
                currentLine.append(if (currentLine.isEmpty()) word else " $word")
            } else {
                if (currentLine.isNotEmpty()) {
                    result.add(currentLine.toString())
                    currentLine = StringBuilder(word)
                } else {
                    // Single word exceeds maxWidth, break word
                    result.add(word)
                    currentLine = StringBuilder()
                }
            }
        }
        if (currentLine.isNotEmpty()) {
            result.add(currentLine.toString())
        }
        return result
    }

    fun openPdf(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
        val intent = Intent(Intent.ACTION_VIEW).apply {
            setDataAndType(uri, "application/pdf")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        try {
            context.startActivity(Intent.createChooser(intent, "Open eBook PDF"))
        } catch (_: Exception) {
            // In case no external PDF viewer is installed
        }
    }

    fun sharePdf(context: Context, file: File, bookTitle: String) {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "Free eBook: $bookTitle")
            putExtra(Intent.EXTRA_TEXT, "Here is the free public-domain PDF of \"$bookTitle\".")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        context.startActivity(Intent.createChooser(intent, "Share eBook PDF"))
    }
}
